version: "3.9"
services:
  updater:
    image: steamcmd/steamcmd
    command: ["+force_install_dir", "/data", "+login", "anonymous", "+app_update", "629800", "+quit"]
    volumes:
      - ./mordhau_data:/data
